# Neural Nets

Loading packages:

In [1]:
using MLDatasets, Images, TestImages, LinearAlgebra

Loading the FashionMNIST data:

In [2]:
train_x, train_y = FashionMNIST.traindata()
test_x, test_y = FashionMNIST.testdata();

Assigning values for our y:

In [3]:
X = []
Y = []

for i = 1:60000
    if train_y[i] == 1 || train_y[i] == 2 || train_y[i] == 3
        
        # Adding 1 to x for bias
        x = push!(copy(reshape(train_x[:, :, i], 784)), 1.0)
        push!(X, x)
        #push!(X, reshape(train_x[:, :, i], 784))
        
        # making y_temp as a vector (-1, -1, -1)
        # this will update to be (-1, 1, -1) for 2 and (-1, -1, 1) for 3, etc.
        y_temp = -1*ones(3)
        y_temp[train_y[i]] = 1
        push!(Y, y_temp)
        
    end
end

Creating the sign function:

In [4]:
function sign(w, x)
    x = push!(copy(x), 1.0)
    return w'x > 0 ? 1 : -1
end

sign (generic function with 1 method)

Creating our weight matrix:

In [5]:
W = rand(3, 785)

3×785 Array{Float64,2}:
 0.837237   0.0427911  0.401778  0.506039  …  0.246931  0.312296  0.278679
 0.0185075  0.342533   0.158236  0.385398     0.333114  0.819907  0.84257 
 0.0264077  0.529631   0.142473  0.49         0.17967   0.786852  0.511922

In [6]:
W*X[1]

3-element Array{Float64,1}:
 91.40665057433888
 98.48770796326654
 93.55780344953014

In [7]:
function sign(s)
    if s > 0
        return 1
    else
        return -1
    end
end

sign (generic function with 2 methods)

Here our sign function is being "broadcasted" to all of the elements of what's inside of the function:

In [8]:
# This is like our 'h'
sign.(W*X[1])

3-element Array{Int64,1}:
 1
 1
 1

In [9]:
sign.(W*X[1]) - Y[1]

3-element Array{Float64,1}:
 2.0
 2.0
 0.0

Updating the weights:

In [24]:
# The previous first two elements were wrong, so fixing them here:
W[1,:] += Y[1][1]*X[1]
W[2,:] += Y[1][2]*X[1];

In [25]:
# Updated now; should be 3 zeroes
sign.(W*X[1]) - Y[1]

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

In [26]:
# This is how many iterations the following for loop will compute
count = size(X)[1]
count

18000

In [27]:
for i = 1:count
    y_hat = sign.(W*X[i])
    
    for j = 1:3
        if y_hat[j] != Y[i][j]
            W[j,:] += Y[i][j]*X[i]
        end
    end
end


In [28]:
sign.(W*X[2]) - Y[2]

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

In [29]:
# If all are correct, error should equal zero
error = 0
for i = 1:count
    error += norm(sign.(W*X[i]) - Y[i])
end

In [30]:
# Calculating the percentage of how off we are
error/(count)*100

0.1801436909112355

In [31]:
# Running again to try and improve the algorithm
for i = 1:count
    y_hat = sign.(W*X[i])
    
    for j = 1:3
        if y_hat[j] != Y[i][j]
            W[j,:] += Y[i][j]*X[i]
        end
    end
end

error = 0
for i = 1:count
    error += norm(sign.(W*X[i]) - Y[i])
end


In [32]:
# Calculating the percentage of how off we are
error/count*100

0.19231103735958058

Not bad, but going to ...

In [33]:
test_X = []
test_Y = []

for i = 1:1000000
    if test_y[i] == 1 || test_y[i] == 2 || test_y[i] == 3
        
        # Adding 1 to x for bias
        x = push!(copy(reshape(test_x[:, :, i], 784)), 1.0)
        push!(test_X, x)
        #push!(X, reshape(train_x[:, :, i], 784))
        
        # making y_temp as a vector (-1, -1, -1)
        # this will update to be (-1, 1, -1) for 2 and (-1, -1, 1) for 3, etc.
        y_temp = -1*ones(3)
        y_temp[test_y[i]] = 1
        push!(test_Y, y_temp)
        
    end
end


In [34]:
count2 = size(test_X)[1]

3000

In [35]:
error = 0
for i = 1:count2
    error += norm(sign.(W*test_X[i]) - test_Y[i])
end

error/count2*100

22.672107351676974

In [36]:
for i = 1:count2
    if norm(sign.(W*test_X[i]) - test_Y[i]) != 0
        println("Error Here:")
        println(sign.(W*test_X[i]))
        println(test_Y[i])
    end
end
error/count2*100

Error Here:
[-1, 1, 1]
[-1.0, 1.0, -1.0]
Error Here:
[-1, 1, 1]
[-1.0, -1.0, 1.0]
Error Here:
[-1, 1, 1]
[-1.0, -1.0, 1.0]
Error Here:
[-1, -1, -1]
[-1.0, 1.0, -1.0]
Error Here:
[-1, 1, 1]
[-1.0, -1.0, 1.0]
Error Here:
[-1, 1, 1]
[-1.0, -1.0, 1.0]
Error Here:
[-1, -1, 1]
[1.0, -1.0, -1.0]
Error Here:
[1, -1, -1]
[-1.0, -1.0, 1.0]
Error Here:
[-1, 1, 1]
[-1.0, -1.0, 1.0]
Error Here:
[-1, 1, -1]
[-1.0, -1.0, 1.0]
Error Here:
[-1, -1, -1]
[1.0, -1.0, -1.0]
Error Here:
[-1, 1, -1]
[-1.0, -1.0, 1.0]
Error Here:
[-1, 1, 1]
[-1.0, -1.0, 1.0]
Error Here:
[-1, 1, 1]
[-1.0, -1.0, 1.0]
Error Here:
[-1, 1, 1]
[-1.0, -1.0, 1.0]
Error Here:
[-1, -1, -1]
[-1.0, -1.0, 1.0]
Error Here:
[-1, -1, 1]
[1.0, -1.0, -1.0]
Error Here:
[-1, 1, 1]
[-1.0, 1.0, -1.0]
Error Here:
[-1, 1, -1]
[-1.0, -1.0, 1.0]
Error Here:
[-1, 1, 1]
[1.0, -1.0, -1.0]
Error Here:
[-1, 1, 1]
[-1.0, -1.0, 1.0]
Error Here:
[-1, 1, -1]
[-1.0, -1.0, 1.0]
Error Here:
[-1, -1, 1]
[-1.0, 1.0, -1.0]
Error Here:
[-1, -1, -1]
[1.0, -1.0, -1.0]


22.672107351676974

In [39]:
error = 0
for i = 1:count2
    if norm(sign.(W*test_X[i]) - test_Y[i]) != 0
        error += 1
    end
end
error/count2*100

9.833333333333332